{
  "name": "Попытка авторизации с неверными данными",
  "status": "passed",
  "steps": [
    {
      "name": "Авторизация пользователя",
      "status": "passed",
      "parameters": [
        {
          "name": "email",
          "value": "'wrong@email.com'"
        },
        {
          "name": "password",
          "value": "'AJ_8sLg%Zz'"
        }
      ],
      "start": 1722303512054,
      "stop": 1722303512668
    },
    {
      "name": "Проверяем код ответа. Код ответа - 401",
      "status": "passed",
      "start": 1722303512668,
      "stop": 1722303512668
    },
    {
      "name": "Проверяем значение поля 'message' в ответе (email or password are incorrect)",
      "status": "passed",
      "start": 1722303512669,
      "stop": 1722303512669
    }
  ],
  "parameters": [
    {
      "name": "email",
      "value": "'wrong@email.com'"
    },
    {
      "name": "password",
      "value": "'correctpassword'"
    }
  ],
  "start": 1722303512054,
  "stop": 1722303512669,
  "uuid": "d26ad9c6-9766-40bd-8c07-208f988058eb",
  "historyId": "832c25a83148f922513088a4ab91a401",
  "testCaseId": "fbeae77312463979bb58e896f211518f",
  "fullName": "tests.test_user_login.TestUserLogin#test_login_with_invalid_credentials",
  "labels": [
    {
      "name": "feature",
      "value": "Авторизация пользователя"
    },
    {
      "name": "tag",
      "value": "negative"
    },
    {
      "name": "parentSuite",
      "value": "tests"
    },
    {
      "name": "suite",
      "value": "test_user_login"
    },
    {
      "name": "subSuite",
      "value": "TestUserLogin"
    },
    {
      "name": "host",
      "value": "PandaPC"
    },
    {
      "name": "thread",
      "value": "4920-MainThread"
    },
    {
      "name": "framework",
      "value": "pytest"
    },
    {
      "name": "language",
      "value": "cpython3"
    },
    {
      "name": "package",
      "value": "tests.test_user_login"
    }
  ]
}